server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8002  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #lb是负载均衡，CLOUD-PAYMENT-SERVICE是注册中心的服务名
          filter:
            - AddRequestParameter=X-Request-Id,1024  # 过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
            - Cookie=username,tom

        - id: payment_route2
          # uri: http://localhost:8002
          uri: lb://cloud-payment-service #lb是负载均衡，CLOUD-PAYMENT-SERVICE是注册中心的服务名
          predicates:
            - Path=/payment/discovery/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7002.com:7002/eureka